### ISSUE TITLE
IndexError: modification of ss-twitterfinal.txt

### ISSUE THREAD

**Issue by ghost** [Deffro/text-preprocessing-techniques#3]
im trying to change the column[1] of ss-twitterfinal.txt file with some other twitter tweets and  column[2] with some other names like label1,label2,....etc..by keeping the structure of the file same.when im compiling the preprocess.py file im getting the error :  
'
Traceback (most recent call last):
  File "c:/Users/admin/Desktop/text-preprocessing-techniques-master/preprocess.py", line 102, in <module>
    y = (columns[2])
IndexError: list index out of range  

please help me regarding it.

**Comment by Deffro** [comment]
If you made no changes in the code please ensure that your dataset has the right format. 3 columns tab separated.
